# NK Celestin Web Application - Kubernetes Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nk-celestin-web-app
  labels:
    app: nk-celestin-web
    maintainer: nk-celestin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nkcelestin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nk-celestin-web-app
            port:
              number: 8080