# NK Celestin Web Application - Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: nk-celestin-web-app
  labels:
    app: nk-celestin-web
    maintainer: nk-celestin
spec:
  type: ClusterIP
  selector:
    app: nk-celestin-web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http